### PR TITLE
List DNS records

### PR DESCRIPTION
**Pull request by carlswart**
The function allows you to do an API call to get a list of all DNS
records for a domain name.

### CODE REVIEW

**Comment by pmill** [comment]
Thanks, would you be able to include an example as well (similar to the existing examples in the repo)?

**Comment by carlswart** [comment]
I've added an example as you have requested.

**Comment by carlswart** [comment]
Hi, 

The example has been added. 


-- 
Regards, 
-Carl 

----- Original Message -----

**Comment by pmill** [comment]
Thanks

**Pull request merged**
